#include QMK_KEYBOARD_H
#include "leds.c"
#include "oneshot.h"
#include <stdio.h>

enum custom_keycodes {
    OS_SHFT = QK_KB_0,
    OS_CTRL,
    OS_ALT,
    OS_GUI,
};

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT( //Alphabet
		KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T,                       XXXXXXX,    XXXXXXX,     KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
		KC_TAB, KC_A, KC_S, KC_D, KC_F, KC_G,                       LCTL(KC_V), LCTL(KC_Z),  KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_ENT,
		KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B,                      LCTL(KC_C), LCTL(KC_X),  KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_DEL,
		XXXXXXX, XXXXXXX, XXXXXXX, KC_LGUI, MO(1), KC_LSFT,         XXXXXXX,    XXXXXXX,     KC_SPC, MO(2), KC_LALT, XXXXXXX, XXXXXXX, XXXXXXX),

	[1] = LAYOUT( //Numpad and Punctuation
		KC_TILD, KC_7, KC_8, KC_9, KC_PDOT, KC_PLUS,                XXXXXXX,    XXXXXXX,     KC_PERC, KC_DLR, KC_EXLM, KC_LCBR, KC_RCBR, KC_DQUO,
		KC_GRV, KC_4, KC_5, KC_6, KC_0, KC_MINS,                    XXXXXXX,    XXXXXXX,     KC_AMPR, KC_HASH, KC_PIPE, KC_LBRC, KC_RBRC, KC_QUOT,
		KC_LCTL, KC_1, KC_2, KC_3, KC_EQL, KC_ASTR,                 XXXXXXX,    XXXXXXX,     KC_BSLS, KC_AT, KC_CIRC, KC_LPRN, KC_RPRN, KC_UNDS,
		XXXXXXX, XXXXXXX, XXXXXXX, KC_LGUI, TO(0), LSFT_T(KC_BSPC), XXXXXXX,    XXXXXXX,     KC_PENT, LGUI(KC_SPC), KC_LALT, XXXXXXX, XXXXXXX, XXXXXXX),

	[2] = LAYOUT( //Punctuation and Arrow key
		KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6,                   XXXXXXX,    XXXXXXX,     KC_PGUP, KC_HOME, KC_UP, KC_END, KC_INS, KC_NUM,
		KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12,                XXXXXXX,    XXXXXXX,     KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_APP, KC_SCRL,
		KC_LCTL, MO(3), XXXXXXX, XXXXXXX, KC_VOLD, KC_VOLU,         XXXXXXX,    XXXXXXX,     KC_MPRV, KC_MNXT, KC_MPLY, KC_MUTE, KC_PAUS, KC_PSCR,
		XXXXXXX, XXXXXXX, XXXXXXX, KC_LGUI, KC_CAPS, KC_LSFT,       XXXXXXX,    XXXXXXX,     KC_SPC, TO(0), KC_LALT, XXXXXXX, XXXXXXX, XXXXXXX),

	[3] = LAYOUT( //
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, TO(0), QK_BOOT, XXXXXXX, XXXXXXX, XXXXXXX,         XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX),

	[4] = LAYOUT( //
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX),

	[5] = LAYOUT( //
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX),

	[6] = LAYOUT( //
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX),

	[7] = LAYOUT( //
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX),

	[8] = LAYOUT( //
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX,    XXXXXXX,     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX)
};
// clang-format on

oneshot_state os_shft_state = os_up_unqueued;
oneshot_state os_ctrl_state = os_up_unqueued;
oneshot_state os_alt_state = os_up_unqueued;
oneshot_state os_gui_state = os_up_unqueued;

bool is_oneshot_cancel_key(uint16_t keycode)
{
    switch (keycode) {
    case KC_ESC:
    case MO(1):
    case MO(2):
        return true;
    default:
        return false;
    }
}

bool is_oneshot_ignored_key(uint16_t keycode)
{
    switch (keycode) {
    case MO(1):
    case MO(2):
    case TO(0):
    case OS_SHFT:
    case OS_CTRL:
    case OS_ALT:
    case OS_GUI:
        return true;
    default:
        return false;
    }
}

bool process_record_user(uint16_t keycode, keyrecord_t* record)
{
    update_oneshot(&os_shft_state, KC_LSFT, OS_SHFT, keycode, record);
    update_oneshot(&os_ctrl_state, KC_LCTL, OS_CTRL, keycode, record);
    update_oneshot(&os_alt_state, KC_LALT, OS_ALT, keycode, record);
    update_oneshot(&os_gui_state, KC_LGUI, OS_GUI, keycode, record);
    return true;
}
